<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="33198" started-at="2016-03-01T14:41:00Z" finished-at="2016-03-01T14:41:33Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="33198" started-at="2016-03-01T14:41:00Z" finished-at="2016-03-01T14:41:33Z">
      <class name="sampleMaven.PractTestSample">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:sampleMaven.PractTestSample@7c75222b]" name="beforeClass" is-config="true" duration-ms="12265" started-at="2016-03-01T14:41:00Z" finished-at="2016-03-01T14:41:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="testSample()[pri:0, instance:sampleMaven.PractTestSample@7c75222b]" name="testSample" duration-ms="20464" started-at="2016-03-01T14:41:12Z" finished-at="2016-03-01T14:41:33Z">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[wrong url]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: wrong url
	at sampleMaven.PractTestSample.testSample(PractTestSample.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSample -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:sampleMaven.PractTestSample@7c75222b]" name="afterClass" is-config="true" duration-ms="447" started-at="2016-03-01T14:41:33Z" finished-at="2016-03-01T14:41:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- sampleMaven.PractTestSample -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
